# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'git@github.com:Flipkart/fk-private-cocoapods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'CoreDataTest' do
    pod 'fk-ios-lib-coredata', :path => "../lib/fk-ios-lib-coredata.podspec"
end

target 'CoreDataTestTests' do
    pod 'fk-ios-lib-coredata', :path => "../lib/fk-ios-lib-coredata.podspec"
end
